Ss=("Question one")
print(Ss)
name=("Ugoala David Osinachi")
print(name)
aa=("science education")
print(aa)
ss=("Question two")
print(ss)
scare=("Boo")
print(scare)
jj=("QuestionThree")
print(jj)
aa=(2)
print(aa)
ss=(3)
print(ss)
ss=(2+3)
print(ss)
aa=("Question four") 
print(aa)
outcome=(12/0.5)
print (outcome)
aa=("Question five")
print(aa)
variable=(2+3)
print(variable)
xx=("Question six")
print(xx)
aa=("modulus %")
print(aa)
aa=("Question seven")
print(aa)
aa=(2*4)*(4+2)
print(aa)